"""
Capability Discovery — unified view of all available tools.

Combines:
  - Tools from installed Skills
  - Tools from active MCPs
  - Tools generated by Forge
  - Built-in core tools (from empire.agent.llm.tools)

Injects a summary into the agent's system prompt so the LLM knows what's available
WITHOUT hardcoding tool definitions in code.
"""
from typing import Dict, List, Any, Optional
from empire.registry.skills import get_registry
from empire.registry.mcps import get_manager
from empire.registry.forge import get_forge


def discover_all_capabilities() -> Dict[str, Any]:
    """Return all capabilities currently available."""
    skills = get_registry()
    mcps = get_manager()
    forge = get_forge()

    skill_caps = skills.get_capability_summary()
    mcp_caps = mcps.get_capability_summary()
    forge_tools = forge.list_tools()

    return {
        "skills": {
            "active": skill_caps["skills_active"],
            "tools": skill_caps["tools"],
            "prompts": skill_caps["prompts"],
            "templates": skill_caps["templates"],
        },
        "mcps": mcp_caps["mcps"],
        "forge": {
            "tools": [t["name"] for t in forge_tools],
            "count": len(forge_tools),
            "total_cost_usd": sum(t.get("cost_usd", 0) for t in forge_tools),
        },
    }


def build_capability_prompt() -> str:
    """Build a system prompt section describing all capabilities."""
    caps = discover_all_capabilities()

    if not caps["skills"]["active"] and not caps["mcps"]["mcps"] and not caps["forge"]["tools"]:
        return ""

    lines = ["## CAPABILIDADES DISPONÍVEIS\n"]

    if caps["skills"]["active"]:
        lines.append("### Skills instaladas e ativas")
        for s in caps["skills"]["active"]:
            lines.append(f"- `{s}`")
        lines.append("")

    if caps["skills"]["tools"]:
        lines.append("### Tools de skills")
        for t in caps["skills"]["tools"]:
            lines.append(f"- `{t['name']}` (skill: {t['skill']})")
        lines.append("")

    if caps["mcps"]["mcps"]:
        lines.append("### MCPs ativos")
        for m in caps["mcps"]["mcps"]:
            status = "online" if m.get("online") else "offline"
            tools_list = ", ".join(m.get("tools", [])) or "(sem tools)"
            lines.append(f"- `{m['name']}` [{status}] → tools: {tools_list}")
        lines.append("")

    if caps["forge"]["tools"]:
        lines.append("### Tools geradas pelo Forge")
        for t in caps["forge"]["tools"]:
            lines.append(f"- `{t}`")
        lines.append("")

    lines.append("Quando precisar executar uma ação, USE as tools acima (não invente novas).")
    lines.append("Se nenhuma tool servir, peça ao usuário permissão para gerar uma nova via Forge.")
    return "\n".join(lines)


def resolve_tool(tool_name: str) -> Optional[Dict[str, Any]]:
    """Find a tool by name across all sources."""
    # 1. Skills
    skill_reg = get_registry()
    found = skill_reg.get_tool_code(tool_name)
    if found:
        code, skill_name, _ = found
        return {"source": "skill", "skill": skill_name, "code": code}

    # 2. Forge
    forge = get_forge()
    tool = forge.get(tool_name)
    if tool:
        return {"source": "forge", "code": tool.code, "tool": tool}

    # 3. MCPs — search across active MCPs
    mcp_mgr = get_manager()
    for srv in mcp_mgr.servers.values():
        if not srv.enabled:
            continue
        for tool_meta in srv.tools:
            if tool_meta.get("name") == tool_name:
                return {"source": "mcp", "mcp": srv.name, "tool": tool_meta}

    return None


def execute_tool(tool_name: str, inputs: Dict[str, Any]) -> Dict[str, Any]:
    """Execute a tool by name, dispatching to the right source."""
    resolved = resolve_tool(tool_name)
    if not resolved:
        return {"success": False, "error": f"tool not found: {tool_name}"}

    source = resolved["source"]
    if source == "skill":
        from empire.registry.sandbox import run_in_sandbox, PROFILES
        result = run_in_sandbox(resolved["code"], inputs=inputs, profile=PROFILES["medium"])
        return {
            "success": result.success,
            "stdout": result.stdout,
            "stderr": result.stderr,
            "duration_ms": result.duration_ms,
        }
    elif source == "forge":
        return get_forge().invoke(tool_name, inputs)
    elif source == "mcp":
        mcp_name = resolved["mcp"]
        try:
            result = get_manager().call_tool(mcp_name, tool_name, inputs)
            return {"success": True, "result": result}
        except Exception as e:
            return {"success": False, "error": str(e)}

    return {"success": False, "error": "unknown source"}


# ─── Singleton ──────────────────────────────────────────────────────────────

_capabilities_cache = None
_cache_ts = 0


def capabilities_snapshot(force_refresh: bool = False) -> Dict[str, Any]:
    """Cached capability snapshot (refreshes every 10s)."""
    global _capabilities_cache, _cache_ts
    now = time.time()
    if force_refresh or now - _cache_ts > 10 or _capabilities_cache is None:
        _capabilities_cache = discover_all_capabilities()
        _cache_ts = now
    return _capabilities_cache


import time
