#!/usr/bin/env bash
#
# pin_digests.sh — resolve every image:tag in docker-compose.yml to a
# pinned image@sha256:digest and write a docker-compose.digests.yml overlay.
#
# Run from the repo root:
#   ./scripts/pin_digests.sh > docker-compose.digests.yml
#
# The output file REPLACES the `image:` directive with `image@sha256:...`.
# This makes the build reproducible (you always get exactly that image
# regardless of what `:latest` points to).
#
set -uo pipefail

COMPOSE="${1:-docker-compose.yml}"
OUT="${2:-docker-compose.digests.yml}"

cat << 'HEADER' > "$OUT"
# AI Empire — Image digest pinning overlay.
#
# Generated by scripts/pin_digests.sh — do not edit by hand.
# Usage:  docker compose -f docker-compose.yml -f docker-compose.digests.yml up -d
#
# Each image:tag below was resolved to a specific SHA256 at generation time.
# Re-run the script to refresh.
#
name: ai-empire-pinned
HEADER

# Resolve a single image:tag to its current digest.
resolve_digest() {
    local img="$1"
    local reg="" repo_tag="$img" repo tag

    if [[ "$img" == *"/"* ]]; then
        first="${img%%/*}"
        if [[ "$first" == *"."* ]] || [[ "$first" == *":"* ]]; then
            reg="$first"
            repo_tag="${img#*/}"
        fi
    fi
    repo="${repo_tag%%:*}"
    tag="${repo_tag##*:}"
    [ "$repo" = "$tag" ] && tag="latest"

    # For Docker Hub, prepend library/ if it's an official image
    if [ -z "$reg" ] || [ "$reg" = "docker.io" ]; then
        if [[ "$repo" != */* ]]; then
            repo="library/$repo"
        fi
        # Get token first (anonymous)
        local token scope="repository:$repo:pull"
        token=$(curl -fsS "https://auth.docker.io/token?service=registry.docker.io&scope=$scope" 2>/dev/null \
                | python3 -c "import json,sys; print(json.load(sys.stdin).get('token',''))" 2>/dev/null || echo "")

        # Pull manifest as OCI index (manifest list) and pick amd64 digest
        local digest
        digest=$(curl -fsS -m 10 \
            -H "Authorization: Bearer $token" \
            -H "Accept: application/vnd.oci.image.index.v1+json,application/vnd.docker.distribution.manifest.list.v2+json,application/vnd.docker.distribution.manifest.v2+json,application/vnd.oci.image.manifest.v1+json" \
            "https://registry-1.docker.io/v2/$repo/manifests/$tag" 2>/dev/null \
            | python3 -c "
import json, sys
m = json.load(sys.stdin)
# OCI index / manifest list — pick amd64 linux
for entry in m.get('manifests', []):
    p = entry.get('platform', {})
    if p.get('architecture') == 'amd64' and p.get('os') == 'linux':
        print(entry['digest'])
        sys.exit(0)
# Fall back to first manifest entry
if m.get('manifests'):
    print(m['manifests'][0]['digest'])
    sys.exit(0)
print('none')
" 2>/dev/null || echo "")
        if [ -z "$digest" ] || [ "$digest" = "none" ]; then
            echo ""
            return
        fi
        echo "$repo@$digest"
    elif [ "$reg" = "ghcr.io" ]; then
        # GitHub Container Registry — anonymous Bearer may fail for some images.
        # If GHCR_TOKEN env var is set, use it; otherwise try anonymous first.
        local token=""
        if [ -n "${GHCR_TOKEN:-${GITHUB_TOKEN:-}}" ]; then
            token="${GHCR_TOKEN:-${GITHUB_TOKEN}}"
        else
            # Try to get an anonymous token via GitHub's endpoint
            token=$(curl -fsS -m 5 \
                -H "Accept: application/vnd.github+json" \
                "https://ghcr.io/token?scope=repository:$repo:pull&service=ghcr.io" 2>/dev/null \
                | python3 -c "import json,sys; print(json.load(sys.stdin).get('token',''))" 2>/dev/null || echo "QQ==")
        fi
        local digest
        digest=$(curl -fsS -m 10 -I \
            -H "Authorization: Bearer $token" \
            -H "Accept: application/vnd.oci.image.index.v1+json,application/vnd.docker.distribution.manifest.list.v2+json" \
            "https://ghcr.io/v2/$repo/manifests/$tag" 2>/dev/null \
            | grep -i "^docker-content-digest:" | awk '{print $2}' | tr -d '\r')
        if [ -z "$digest" ]; then
            digest=$(curl -fsS -m 10 -I \
                -H "Authorization: Bearer $token" \
                -H "Accept: application/vnd.oci.image.index.v1+json" \
                "https://ghcr.io/v2/$repo/manifests/$tag" 2>/dev/null \
                | grep -i "^docker-content-digest:" | awk '{print $2}' | tr -d '\r')
        fi
        if [ -z "$digest" ]; then echo ""; return; fi
        echo "$repo@$digest"
    else
        # Generic registry — use HEAD on manifest
        local digest
        digest=$(curl -fsS -m 10 -I \
            -H "Accept: application/vnd.oci.image.index.v1+json,application/vnd.docker.distribution.manifest.list.v2+json" \
            "https://$reg/v2/$repo/manifests/$tag" 2>/dev/null \
            | grep -i "^docker-content-digest:" | awk '{print $2}' | tr -d '\r')
        if [ -z "$digest" ]; then echo ""; return; fi
        echo "$repo@$digest"
    fi
}

# Extract images from compose
IMAGES=$(awk '
  /^[[:space:]]*image:/ {
    line = $0
    sub(/^[[:space:]]*image:[[:space:]]*/, "", line)
    sub(/[[:space:]]*#.*$/, "", line)
    gsub(/['"'"'"]/, "", line)
    if (line != "") print line
  }
' "$COMPOSE" | sort -u)

# Print the services section header
cat << 'EOF' >> "$OUT"

services:
EOF

count_ok=0; count_fail=0
for img in $IMAGES; do
    printf "  resolving %s ... " "$img"
    pinned=$(resolve_digest "$img" 2>/dev/null)
    if [ -z "$pinned" ]; then
        echo "FAILED (image or registry unreachable)"
        count_fail=$((count_fail+1))
        continue
    fi
    echo "ok → $pinned"
    count_ok=$((count_ok+1))

    # Service name: strip registry prefix, use last path component
    svc="$img"
    # If has registry (e.g. ghcr.io/foo/bar or library/foo), strip it
    if [[ "$svc" == *"/"* ]]; then
        first="${svc%%/*}"
        if [[ "$first" == *"."* ]] || [[ "$first" == *":"* ]]; then
            svc="${svc#*/}"
        fi
    fi
    # Now use last path component as service name
    svc="${svc%%/*}"
    # Strip :tag
    svc="${svc%%:*}"
    # Sanitize for YAML key (replace : with -)
    svc="${svc//:/-}"
    # Strip registry prefix from pinned if it's library/...
    cat << EOF >> "$OUT"
  $svc:
    image: $pinned
EOF
done

cat << EOF >> "$OUT"

# Generation metadata
generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
resolved_ok: $count_ok
resolved_fail: $count_fail
EOF

echo
echo "Wrote $OUT ($count_ok pinned, $count_fail failed)"
echo "FAILED images (need manual fix):"
for img in $IMAGES; do
    pinned=$(resolve_digest "$img" 2>/dev/null)
    if [ -z "$pinned" ]; then
        echo "  $img"
    fi
done 2>/dev/null

[ $count_fail -eq 0 ]
